name: QA

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  qa:
    uses: HariniMuruganantham/Automatic-QA-CiCd/.github/workflows/master-qa.yml@main
    with:
      project-name: "harini-devops-portfolio"
      base-url: "https://harini-devops-portfolio.vercel.app"
      openai-model: "gpt-4o-mini"
      run-load: true
      run-stress: false
      load-vus: 20
    secrets:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}